### ISSUE TITLE
Frequencia da portaria

### ISSUE THREAD

**Issue by riquetinem** [igsis/simbi#19]
Armazenar o nome/nome social

**Comment by DiegoVSantos** [comment]
[Planilha Exemplo](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b7efa5324364700133ca753/125516c66e82c728ace21e0d46c1baa917b0b684aac78b628862a1d665043761260ea62864c7b96aea402c04095a4ca8105f0a43f5ad892ba7e33f238d5903ecc3714d36976345f3e5db55ea43a82a994e8dbcbd8f4fc5e13427e28c8f4d3b1a1755.pdf)
