### ISSUE TITLE
Frequência portaria COMPLETA

### ISSUE THREAD

**Issue by riquetinem** [igsis/simbi#20]
Armazenar o nome/nome social
sexo
escolaridade
idade: 0 a6, 7 a 14, 15 a 17, 18 a 29, 30 a 59 , 60 ou mais
cor/raça: amarela, branca, indigena, parda e preta
deficiencia: cega (visual)
escolaridade: fundamental, medio e superior

**Comment by DiegoVSantos** [comment]
[INSTRUMENTAL_2.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b7efa5324364700133ca753/125516c66e82c728ace21e0d46c1baa917b0b684aac78b628862a2d665043761260ea62864c7b96aea402c04095a4ca8105f0a43f5ad892ba7e33f238d5903ecc3714d36976345f3e5db55ea43a82a994e8dbcbd8f4fc5e13427e28b8b493b171755.pdf)
